# Generated by Django 3.2 on 2022-12-22 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('golf_club_name', models.CharField(max_length=254, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('course', models.CharField(default='New Course', max_length=80, unique=True)),
                ('descripton', models.CharField(max_length=500, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/')),
            ],
            options={
                'ordering': ['golf_club_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('requested_date', models.DateField()),
                ('requested_time', models.CharField(choices=[('09:00', '09:00'), ('09:10', '09:10'), ('09:20', '09:20'), ('09:30', '09:30'), ('09:40', '09:40'), ('09:50', '09:50'), ('10:00', '10:00'), ('10:10', '10:10'), ('10:20', '10:20'), ('10:30', '10:30'), ('10:40', '10:40'), ('10:50', '10:50'), ('11:00', '11:00'), ('11:10', '11:10'), ('11:20', '11:20'), ('11:30', '11:30'), ('11:40', '11:40'), ('11:50', '11:50'), ('12:00', '12:00'), ('12:10', '12:10'), ('12:20', '12:20'), ('12:30', '12:30'), ('12:40', '12:40'), ('12:50', '12:50'), ('13:00', '13:00'), ('13:10', '13:10'), ('13:20', '13:20'), ('13:30', '13:30'), ('13:40', '13:40'), ('13:50', '13:50'), ('14:00', '14:00'), ('14:10', '14:10'), ('14:20', '14:20'), ('14:30', '14:30'), ('14:40', '14:40'), ('14:50', '14:50'), ('15:00', '15:00'), ('15:10', '15:10'), ('15:20', '15:20'), ('15:30', '15:30'), ('15:40', '15:40'), ('15:50', '15:50'), ('16:00', '16:00'), ('16:10', '16:10'), ('16:20', '16:20'), ('16:30', '16:30'), ('16:40', '16:40'), ('16:50', '16:50')], default='12:00', max_length=25)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('status', models.CharField(choices=[('Tee Time Confirmed', 'Tee Time Confirmed'), ('Tee Time Rejected', 'Tee Time Rejected'), ('Tee Time Expired', 'Tee Time Expired')], default='Tee Time Confirmed', max_length=25)),
                ('player_count', models.IntegerField(choices=[(1, '1 Player'), (2, '2 Players'), (3, '3 Players'), (4, '4 Players')], default=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_course', to='bookings.club')),
                ('golf_club_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_name', to='bookings.club')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_time'],
                'unique_together': {('requested_date', 'requested_time', 'course')},
            },
        ),
    ]
