# Generated by Django 3.2 on 2022-12-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20221222_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='descripton',
            new_name='description',
        ),
    ]
