# Generated by Django 3.2 on 2022-12-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_descripton_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
