# Generated by Django 3.2 on 2022-12-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_club_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
