# Generated by Django 3.2 on 2023-06-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_booking_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('requested_date', 'requested_time', 'golf_club_name')},
        ),
    ]
